<#-- 
 ~ Copyright 2023 Mayeku Khisa
 ~
 ~ Use of this source code is governed by a MIT license as appearing in the
 ~ LICENSE file included in the root of this source tree.
 -->
import Head from "next/head"

import styles from "@/styles/home.module.css"

export default function Home(): JSX.Element {
   return (
      <>
         <Head>
            <title>${projectName}</title>
            <meta name="description" content="Generated by Skeleton" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <p className={styles.catchphrase}>Catchphrase 😎</p>
         </main>
      </>
   )
}
